webtalk_init -webtalk_dir /home/s/ee/ebaz4205/project_1/project_1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-11-28 02:10:35" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "juf6gitgl0c0l61kfo81hg73g3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700 Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1336.459 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.830 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1606499662000" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key hwid -value "1606316329000" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key bspid -value "1606316459000" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key projSize -value "750.34765625" -context "sdk\\\\application/1606499662000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1606500635594"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1606500635594"
webtalk_add_data -client sdk -key BootgenCount -value "1" -context "sdk\\\\bsp/1606500635594"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1606500635594"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1606500635594"
webtalk_add_data -client sdk -key FlashCount -value "2" -context "sdk\\\\bsp/1606500635594"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1606500635594"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1606500635594"
webtalk_transmit -clientid 3458998641 -regid "" -xml /home/s/ee/ebaz4205/project_1/project_1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/s/ee/ebaz4205/project_1/project_1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/s/ee/ebaz4205/project_1/project_1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
